language: node_js
node_js:
  - "0.10"
before_script:
  - wget https://phantomjs.googlecode.com/files/phantomjs-1.9.1-linux-i686.tar.bz2
  - tar -xf phantomjs-1.9.1-linux-i686.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-1.9.1-linux-i686 /usr/local/phantomjs
  - npm install -g grunt-cli